language: python
install: pip install tox
script: tox -e $TOX_ENV
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27-django111

    - python: 3.5
      env: TOX_ENV=py35-django111

    - python: 3.5
      env: TOX_ENV=py35-django20

    - python: 3.6
      env: TOX_ENV=py36-django111

    - python: 3.6
      env: TOX_ENV=py36-django20

    - python: 3.7
      env: TOX_ENV=py37-django111

    - python: 3.7
      env: TOX_ENV=py37-django20

    - python: 3.7
      env: TOX_ENV=py37-django22

    - python: 3.8
      env: TOX_ENV=py38-django111

    - python: 3.8
      env: TOX_ENV=py38-django20

    - python: 3.8
      env: TOX_ENV=py38-django22

    - python: 2.7
      env: TOX_ENV=lint
